source 'https://rubygems.org'
ruby '2.3.1'

gem 'aruba', '~> 0.5.4'
gem 'cucumber', '1.3.10'
gem 'rspec', '2.14.1'
gem 'rspec-core', '2.14.7'
gem 'rspec-expectations', '2.14.4'
gem 'rspec-mocks', '2.14.4'
